### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by ptitodd** [lebaston100/MIDItoOBS#4]
Just followed your instructions step by step and am receiving the following error when running setup.py

Looks like it cannot find _rtmidi module I will dig into the script to see why it's not working. but something doesn't seem to be working right.

OBS 21.0.1
Websocket Server 4.3.3
Windows 10 Pro v1709 build 16299.248
Python 3.6.5

```
C:\Users\todd\MIDItoOBS>python setup.py
MIDItoOBS made by lebaston100.de
!!MAKE SURE OBS IS RUNNING OR THIS SCRIPT WILL CRASH!!
Select Midi Device
Traceback (most recent call last):
  File "setup.py", line 537, in <module>
    deviceList = mido.get_input_names()
  File "C:\Users\todd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mido\backends\backend.py", line 168, in get_input_names
    devices = self._get_devices(**self._add_api(kwargs))
  File "C:\Users\todd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mido\backends\backend.py", line 161, in _get_devices
    if hasattr(self.module, 'get_devices'):
  File "C:\Users\todd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mido\backends\backend.py", line 41, in module
    self.load()
  File "C:\Users\todd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mido\backends\backend.py", line 57, in load
    self._module = importlib.import_module(self.name)
  File "C:\Users\todd\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\todd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mido\backends\rtmidi.py", line 8, in <module>
    import rtmidi
  File "C:\Users\todd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\rtmidi\__init__.py", line 4, in <module>
    from ._rtmidi import *  # noqa
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by ptitodd** [comment]
Since Python-RTMidi is a wrapper for RTMidi, which is a C++ library. I tried to install regular RTMidi using pip and got an error stating that I needed Visual Studio Build Tools v14 installed. Installed Visual Studio Build Tools from MS and everything started working again. Nothing wrong with the code. I think an update to the Readme might be all that's required.

**Comment by ptitodd** [comment]
I will leave this issue open just for lebaston100 to verify if solution is accurate.

**Comment by lebaston100** [comment]
Sorry for not responding, i still have no idea how why i don't get a notification as the repository owner when an issue is created. Guess i have to watch my own project then. 
I will check your solution on a new win 10 vm and update the readme if necessary.

**Comment by ptitodd** [comment]
Thanks,

Let me know if that isn't the solution, and I'll help troubleshoot.

**Comment by lebaston100** [comment]
ok, so after trying around a little bit it seems enough if you install the Visual Studio 2017 x86 redistributable (for default python 32bit) before installing python-rtmidi via pip.
https://aka.ms/vs/15/release/vc_redist.x86.exe
Can you verify this?

**Comment by ptitodd** [comment]
The visual studio build tools does install this redistributable. So I'm 90% sure that is the solution. But I will verify this evening on a vanilla physical win10 box.

**Comment by lebaston100** [comment]
Any update?

**Comment by lebaston100** [comment]
Closing this now. I've added a troubleshootingsection to the readme: https://github.com/lebaston100/MIDItoOBS/commit/04f51065b41e87aefaeb2f4785531d0898618133

**Comment by ptitodd** [comment]
Yes my apologies on not getting back. I forgot to update you. but can confirm that fixed the issue.

**Comment by lebaston100** [comment]
No problem, Thanks.
